// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyfmxPg3lBhfxcKrAx31lLCEVQ5Ld0anU',
    appId: '1:935339201562:web:61700c468f80ad793ceda3',
    messagingSenderId: '935339201562',
    projectId: 'my-porto-app',
    authDomain: 'my-porto-app.firebaseapp.com',
    storageBucket: 'my-porto-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv2G__48DiQ-OAd1m3n-HpKtJbcOA9q-0',
    appId: '1:935339201562:android:ba68640e0abbab793ceda3',
    messagingSenderId: '935339201562',
    projectId: 'my-porto-app',
    storageBucket: 'my-porto-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1TRUeBl5u2E-f7raj5C0sTlOh2o1yW2M',
    appId: '1:935339201562:ios:72876011070ee91d3ceda3',
    messagingSenderId: '935339201562',
    projectId: 'my-porto-app',
    storageBucket: 'my-porto-app.firebasestorage.app',
    iosBundleId: 'com.example.notePad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1TRUeBl5u2E-f7raj5C0sTlOh2o1yW2M',
    appId: '1:935339201562:ios:72876011070ee91d3ceda3',
    messagingSenderId: '935339201562',
    projectId: 'my-porto-app',
    storageBucket: 'my-porto-app.firebasestorage.app',
    iosBundleId: 'com.example.notePad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyfmxPg3lBhfxcKrAx31lLCEVQ5Ld0anU',
    appId: '1:935339201562:web:4d180c3f77a33e483ceda3',
    messagingSenderId: '935339201562',
    projectId: 'my-porto-app',
    authDomain: 'my-porto-app.firebaseapp.com',
    storageBucket: 'my-porto-app.firebasestorage.app',
  );
}
